Python 2.5.4 (r254:67916, Dec 23 2008, 15:19:34) [MSC v.1400 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.

    ****************************************************************
    Personal firewall software may warn about the connection IDLE
    makes to its subprocess using this computer's internal loopback
    interface.  This connection is not visible on any external
    interface and no data is sent to or received from the Internet.
    ****************************************************************
    
IDLE 1.2.4      
>>> def operador():
	4.0/10.0+3.5*2=
	
SyntaxError: invalid syntax
>>> 
>>> range(5)
[0, 1, 2, 3, 4]
>>> 
>>> range(3,10)
[3, 4, 5, 6, 7, 8, 9]
>>> range(4,13,3)
[4, 7, 10]
>>> range(15,5,-2)
[15, 13, 11, 9, 7]
>>> range(5,3)ç
SyntaxError: invalid syntax
>>> range(5,3)
[]
>>> []
[]
>>> 
>>> 

>>> 


>>> 

>>> 


>>> 

>>> 


>>> 

>>> 


>>> range (5, 3)
[]
>>> for in range (1,11):
	
SyntaxError: invalid syntax
>>> range(5,3)
[]
>>> for in range (1,11):
	
SyntaxError: invalid syntax
>>> def ejercicio():
	for in range(1,11):
		
SyntaxError: invalid syntax
>>> for in range (1.11):
	
SyntaxError: invalid syntax
>>> for i in range(1,11):
	print i*i

	
1
4
9
16
25
36
49
64
81
100
>>> for i in (1,3,5,7,9):
	print i,":",i**3
	print i

	
1 : 1
1
3 : 27
3
5 : 125
5
7 : 343
7
9 : 729
9
>>> X=2
>>> Y=10
>>> for i in range(1,11):
	ans=ans +i*i
    print ans
    
  File "<pyshell#38>", line 3
    print ans
            
^
IndentationError: unindent does not match any outer indentation level
>>> for i in range (1,11):
	ans=ans+i*i
    print ansç
    
  File "<pyshell#41>", line 3
    print ansç
             
^
IndentationError: unindent does not match any outer indentation level
>>> 
>>> ç

Traceback (most recent call last):
  File "<pyshell#43>", line 1, in <module>
    ç
NameError: name 'ç' is not defined
>>> ç

Traceback (most recent call last):
  File "<pyshell#44>", line 1, in <module>
    ç
NameError: name 'ç' is not defined
>>> for i in range (1,11):
	ans=ans+i*i
    print ans
    
  File "<pyshell#45>", line 3
    print ans
            
^
IndentationError: unindent does not match any outer indentation level
>>> 
>>> 
>>> 
>>> x=2
>>> y=10
>>> for i in range(1,11):
	ans=ans+i*i
    print ans
    
  File "<pyshell#53>", line 3
    print ans
            
^
IndentationError: unindent does not match any outer indentation level
>>> 
>>> 
